### ISSUE TITLE
Exclude some accessories

### ISSUE THREAD

**Issue by gponceau** [rsauget/homebridge-flexom#1]
Hi,

First of all, thank you very much for this plugin which is very helpful and complete ! I was looking for that for a very long time and thank you so much !

I would like to know if there is a way to exclude some accessories. Because currently, if I put my ID and password, it brings with all accessories (bulbs and rolling shutters) and with empty zones. I would like to import, for example in my case, only rolling shutters (neither empty rooms nor bulbs). Do you know how could I do that and if I could ?

**Environment:**

* **Plugin Version**: v1.0.7
* **Homebridge Version**: v1.1.6
* **Node.js Version**: v12.19.0
* **NPM Version**: v6.14.8
* **Operating System**: Raspbian (Raspberry-pi)

**Comment by rsauget** [comment]
Hi,
Thanks for the feedback !
Please note that this project (and the underlying flexom-lib) are not yet fully functional nor reliable.
Now on to your question : I need a bit of clarification.
Currently the plug-in only maps Flexom zones as HomeKit accessories, as a LightBulb and/or WindowCovering depending on which factor is available on the zone.
Individual accessory support is not possible yet because I have not reverse-engineered Flexom APIs to do that.

So if I understand correctly you would want to 
- exclude zones with neither light nor window control (empty zones)
- only show bulbs and not window coverings ? Would you see it as a global setting or a per-zone one ?

**Comment by gponceau** [comment]
Hi,
Aaaah ! Ahah ! Ok 😄 So yes, we are 2 now and it runs perfectly fine for me and I waited for this for a so long time so thank you again 🙏

So, what I said is correct for the first point. And I rent my appartment so I have no freedom on flexom app (of course, I won’t keep this room otherwise and to be honest, I don’t know why there are here because some of them doesn’t exist in my appartment 😅)
For the second point, it’s the opposite ^^ I want to keep my window covering but not my bulbs. Indeed, I already have Philips Hue and it interfers with the power of my Philips Hue when the Flexom bulbs are added in my appartment. So it’s not ideal to speak with Siri with that 😅
And do you have any way that I could make you a donation to thank you for the time you spent on that ?
And if you want, we could speak in french because Flexom is a Bouygues system so I’m not sure that english people will be interested in our conversation 😉
Thank you so much again !

**Comment by rsauget** [comment]
C'est vrai qu'il y a peu de chance d'avoir des anglophones ici 😅 

C'est le premier projet que je publie et je ne pensais pas qu'il servirait à quelqu'un !
Je n'ai pas beaucoup de temps pour ce projet et il est encore bien bugué (notamment j'ai besoin de redémarrer homebridge de temps en temps car aucune commande Flexom ne répond plus, je n'ai pas encore trouvé pourquoi...).

C'est bien que tu aies un profil différent sur Flexom (je suis propriétaire occupant), ça permettra de mieux tester tout ça.

Je peux tout à fait exclure les zones vide, c'est vrai que ça ne sert à rien de les importer, je n'y avais pas pensé puisque je les ai supprimées chez moi (mais à la livraison c'était n'importe quoi je te confirme).

Je comprends ton point pour les lumières Hue, j'en ai certaines mais pas toutes et je galère parfois à jongler entre les deux, je n'ai pas encore trouvé de solution satisfaisante.
En tout cas je dois pouvoir facilement ajouter une option dans les paramètres du plugin pour limiter le type d'accessoire importé (lumière, volets ou les deux).

Je n'ai pas besoin de donation pour avancer sur ce projet qui me sert à moi aussi, mais si tu y tiens voici mon lien PayPal : https://paypal.me/rsauget1

**Comment by gponceau** [comment]
Ah bah super premier projet alors. Hâte de voir ce que cela finira par donner et ravi de pouvoir aider (enfin à mon niveau 😅)

J’ai eu le bug dont tu parlais hier soir aussi. Les commandes ont cessés de répondre et redémarrage de homebridge aussi pour que ça refonctionne 😉

En tout cas, respect, car effectivement Flexom m’a l’air bien compliqué comme système.

Ok. Ce serait top en tout cas si c’était possible 👍

Et si je peux aider sur ce projet d’une tout autre manière (car je ne sais pas développer), tu me dis. J’en serais ravi 😃

**Comment by rsauget** [comment]
Je viens de mettre en ligne la version 1.0.9 qui exclut les pièces vide, et devrait corriger le bug (l'authentification Flexom expire au bout de 12h, a priori c'était ça).
Tu pourras tester et me dire si ça marche bien pour toi ?

**Comment by gponceau** [comment]
Je viens de regarder (je n’étais pas chez moi ces derniers jours). C’est bon pour les pièces vides. Super ! Et pour les déconnexions au bout de quelques jours, c’est l’avenir qui nous le dira mais pour l’instant, ça marche :)

**Comment by gponceau** [comment]
Salut !
Je vois que tu as clôturé le fil. Du coup, tu ne comptes plus donner la possibilité d’exclure certains types d’accessoires ?
En tout cas, ça marchait bien ce que tu avais résolu pour les déconnexions régulières. Plus de problème à ce niveau-là.
Merci en tout cas pour ce que tu auras fait 👍

**Comment by rsauget** [comment]
Au temps pour moi, j'avais oublié ce point. Je regarde à l'occasion !

**Comment by gponceau** [comment]
Ahah. Ok. Thank you 😊

**Comment by wcastand** [comment]
Je suppose que l'on est 3 maintenant. je n'ai aucun contrôle sur l'app aussi et du coup j'ai la liste qui apparait dans Home App mais ca me dit que rien n'est compatible.
de ce que je vois dans les rooms: j'ai volets, lumière et chauffage.
une idee de pourquoi je ne peux rien faire dans `Home App` maigres que les rooms soit listées ?

**Comment by rsauget** [comment]
@wcastand Bonjour, peux-tu stp créer une issue pour ton problème qui est différent ?
Avec des captures d'écran si possible, j'ai du mal a comprendre ce qui se passe en lisant ton message.
Merci !

**Comment by rsauget** [comment]
@gponceau Hello ! Je viens de publier la 2.1.1 avec l'option pour exclure des pièces.
Tu as besoin de leur id Flexom, que tu peux trouver en faisant un appui long sur l'icone dans l'appli Maison, puis sur l'engrenage en bas à droite,  et en défilant tout en bas.

**Comment by gponceau** [comment]
Super ! Merci beaucoup ! Ça m'enlève beaucoup d'accessoires ! Je t'ai donc envoyé un petit don pour te remercier des tes efforts sur cette mise à jour. 
Il ne me reste plus qu'un accessoire (que je pourrais supprimer quand (et si) l'option d'exclure les accessoires sera possible). Car dans le salon, j'ai le volet (qui m'intéresse) et toujours le contacteur de la lumière. Mais si je supprime la pièce, je supprime également le volet. Mais rien d'urgent, tu feras ça quand tu auras le temps. Tu as déjà fait beaucoup :-) Merci pour tout en tout cas !

**Comment by rsauget** [comment]
@gponceau Merci !
Et tu devrais pouvoir exclure uniquement la lumière avec la 2.2.0 que je viens de publier 😉 
Quand tu ajoutes une pièce à exclure tu peux ne cocher d'exclure que la lumière et/ou les volets.

**Comment by gponceau** [comment]
Génial ! Effectivement, ça marche ! C'est top. Tout est parfait dans Homekit et plus de problèmes quand on dit "éteins toutes les lumières" à Siri. Merci infiniment ! 😃
Je peux donc clôturer vu que tout est résolu de mon côté 😉
