### ISSUE TITLE
Impossible de contrôler les IoT

### ISSUE THREAD

**Issue by wcastand** [rsauget/homebridge-flexom#3]
Je viens de setup Homebridge.
Mon appartement est équipé avec flexom, j'ai installer le plugin et sur la Home app j'ai a liste de mes rooms mais je ne peux rien faire dessus. les 3 screenshots montre mon app flexom avec la liste  des `rooms` et des `things` 
![IMG_010C7F7226D6-1_result](https://user-images.githubusercontent.com/2178244/113487163-c1b8bb00-94b6-11eb-8241-36065a15e3ab.jpg)
![4D3B7152-B7ED-4778-81BA-5989BA00437E_result](https://user-images.githubusercontent.com/2178244/113487068-30e1df80-94b6-11eb-89fd-890ba85ff5e6.png)
![019ED18E-445E-4A86-8AF9-601E811257E4_result](https://user-images.githubusercontent.com/2178244/113487070-317a7600-94b6-11eb-892a-70b057f8fc94.png)

Celui-la montre dans `Home App` la liste des rooms mais me marque qu'elles sont incompatibles.
![B83FE6FB-17CA-43A9-9000-EAF7F172064C_result](https://user-images.githubusercontent.com/2178244/113487071-32130c80-94b6-11eb-855f-c195f796a574.png)

Dans Homebridge il n'y a rien qui apparait
<img width="707" alt="Screenshot 2021-04-03 at 19 59 30" src="https://user-images.githubusercontent.com/2178244/113487221-207e3480-94b7-11eb-870c-e292193c3b60.png">

**Comment by rsauget** [comment]
@wcastand merci pour l'issue 🙏 
Peux-tu préciser la version de @rsauget/homebridge-flexom que tu utilises ?
Si ce n'est pas la 2.0.1 je te propose de mettre à jour pour commencer.
Ensuite, idéalement il me faudrait les logs, que tu peux télécharger depuis l'interface de homebridge (https://github.com/oznu/homebridge-config-ui-x).

**Comment by wcastand** [comment]
j'utilise `@rsauget/homebridge-flexom v2.0.1`, je viens de l'installer aujourd'hui
voici les logs a partir de l'installation du plugin
[homebridge.log.txt](https://github.com/rsauget/homebridge-flexom/files/6253181/homebridge.log.txt)

**Comment by rsauget** [comment]
@wcastand je viens de me rendre compte qu'au premier lancement les zones ne démarrent pas correctement.
Est-ce que tu as essayé de redémarrer homebridge ?

**Comment by rsauget** [comment]
Tu peux essayer d'installer la 2.1.0 et refaire le test (avec logs) ?

**Comment by wcastand** [comment]
updated et restart du serveur mais dans `Home App` ils sont toujours `not supported`
[homebridge.log-2.txt](https://github.com/rsauget/homebridge-flexom/files/6253309/homebridge.log-2.txt)

**Comment by rsauget** [comment]
Je viens de pousser la 2.1.1 qui ajoute un peu de logs, j'espère pouvoir y voir plus clair comme ça.
Si ça ne mène à rien, je compte faire un outil pour tester en ligne de commande la connexion aux API Flexom, j'espère que ça pourra nous aider à débugger.
Merci de ta compréhension.

**Comment by wcastand** [comment]
log 2.1.1:
[homebridge.log-3.txt](https://github.com/rsauget/homebridge-flexom/files/6253387/homebridge.log-3.txt)

juste pour que tu es une idée de ce que les rooms peuvent contenir, il y a volet roulant / lumière et chauffage dans certaines.
![IMG_26CE2C4E64FA-1](https://user-images.githubusercontent.com/2178244/113491363-71e6ed80-94d0-11eb-87df-635827cabec9.jpeg)

**Comment by rsauget** [comment]
Très étrange cette erreur...
Pourrais-tu utiliser la commande suivante :
```
npx @rsauget/flexom-lib
```
Et me fournir ce qu'elle sort ?
C'est le detail des pièces renvoyées par l'API Flexom, ça m'aiderait à mieux comprendre.

**Comment by wcastand** [comment]
[flexon.log](https://github.com/rsauget/homebridge-flexom/files/6253512/flexon.log)

**Comment by wcastand** [comment]
[flexon.log](https://github.com/rsauget/homebridge-flexom/files/6253513/flexon.log)

**Comment by rsauget** [comment]
@wcastand Hello, pour avancer, peux-tu installer la 2.2.1, et activer le mode debug de homebridge ? (dans l'UI, les 3 points en haut a droite, Homebridge Settings, activer "Homebridge Debug Mode -D"
Et me renvoyer un log ?

**Comment by wcastand** [comment]
https://gist.github.com/wcastand/058966aa44eaa6a7082c861cfff6576c

**Comment by rsauget** [comment]
@wcastand d'un coup j'y pense : tu as bien activé l'option "Show Flexom Zones" dans la configuration ?
Sinon tu peux m'envoyer ta config ? En enlevant bien les identifiants Flexom bien sûr 😉

**Comment by wcastand** [comment]
ok ben je viens d'activer les flexom zones et on est bon, ca fonctionne now. J'ai du le désactiver en essayant de trouvais ce qui ne fonctionne pas. my bad :)

**Comment by rsauget** [comment]
Parfait !
Je laisse l'issue ouverte pour me rappeler de :
- mettre un warning dans le log quand tout est désactivé
- supprimer les accessoires inutilisés dans ce cas
