### ISSUE TITLE
Update flexom-lib w/ updated ws delay fix + homebridge-flexom w/ latest flexom-lib

### ISSUE THREAD

**Issue by valeriansaliou** [rsauget/homebridge-flexom#67]
Hello there!

Would it be possible to release all changes from `flexom-lib` master and update `homebridge-flexom` with the new version of the library?

I'm using `homebridge-flexom` on a daily basis at my home (thanks a ton, it does work great!), and I think that having the WS channel send less frequent keep-alives and pings would be nice.

~~BTW quick side-question: when building `flexom-lib`, did you see any way the smoke detector data could be fetched from Flexom API? I have a connected smoke detector at home, which is available through the Flexom app. Could be super useful to have it appear in HomeKit, w/ smoke alerts coming in as well!~~ — Opened issue #68 for this one.

Thanks again for your work!

Valerian.

**Comment by rsauget** [comment]
Hi @valeriansaliou 👋 
I just released `flexom-lib@3.3.0` & `homebridge-flexom@3.1.0` 👍

**Comment by valeriansaliou** [comment]
Hey! Thank you, it does work. :)
