### ISSUE TITLE
Ability to configure accessory state poll interval in seconds (lights + blinds)

### ISSUE THREAD

**Issue by valeriansaliou** [rsauget/homebridge-flexom#8]
The default poll interval of 60s results in frequent rate-limiting from Flexom's APIs (429), which persists and requires an Homebridge plugin stop then wait, then restart.

I've checked at this module's source code and found out that 1 equipment polled = 1 HTTP request out. I assume large homes with a lot of rooms and IoT devices will result in frequent 429s. I've adjusted the poll interval to 600s in the code, which fixed my rate limiting issues.

A solution to this could be to let the user configure the poll interval, just as https://www.npmjs.com/package/homebridge-dyson-pure-cool does (the homebridge-nest-cam plugin also does that). That way, the more IoT equipments one has, the more the poll interval can be increased. Which alleviates all rate-limiting issues.

I'd be happy submitting a PR if you're interested.

**Comment by rsauget** [comment]
Hi,
Ubiant provided me with API docs and it appears they have a websocket system to listen for events.
I published release 3.0.0-beta.1 using this websocket and removing all pollers.
Can you give it a try?

**Comment by valeriansaliou** [comment]
Hello,

Just tried 3.0.0-beta.3. Controls from the Home app are working fine as before.

However, with the addition of the WS service I'd expect Ubiant's WS server to push a light on/off event as soon as a I press the manual mechanical light control switch on the wall, which does not seem to be the case. There's no instant switch in the Home app, nor any log in Homebridge telling about the change of state from true to false or the other way. Is that expected?

**Comment by rsauget** [comment]
That is not implemented yet, indeed.
I need some more time 😉
However, whenever you leave and re-open Home app (or Control Center for that matter), state is refreshed.

**Comment by valeriansaliou** [comment]
If you need some help with this, let me know :)

**Comment by rsauget** [comment]
Hi @valeriansaliou,
v3.0.0 final release is out 🎉 
Event listener is now available, so device state should update in Home app from external action.

**Comment by valeriansaliou** [comment]
Excellent! Thanks for everything, upgrading right now :)
